### ISSUE TITLE
Release fixes to PyPI?

### ISSUE THREAD

**Issue by projx** [inexio/pysnmp#2]
Hi

Glad to see this has been picked, will you be releasing any updates as PyPI packages?

Thanks

**Comment by Lostboi** [comment]
Hey @projx,

we are currently trying to [claim](https://github.com/pypa/pypi-support/issues/802) the repository of Ilya on pypi to publish a newer version of pysnmp and other projects of him. He sadly didnt answer us for almost a year, we dont know whats going on with hin, and we wish that he is coming back soon.

If our claim is successful, we will build instantly a new release for pysnmp. And for all other projects.

Thanks for asking, we will inform you if we got new messages.
